name: Manual Component Test (Color)
description: Script for testing the colors used in an individual component.
title: "[Component Name] Color Test"
labels: ["accessibility", "test", "color"]
body: 
  - type: input
    id: url
    attributes:
      label: Component location
      description: A URL to the canonical version of the component in the design system.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        For testing contrast, use a desktop tool like [Colour Contrast Analyser](https://www.tpgi.com/color-contrast-checker/) or an online service like [colourcontrast.cc](https://colourcontrast.cc/). The contrast ratios expected are:

        * Text versus background: `4.5:1`^
        * Non-text interface elements versus background: `3:1`

        If text is superimposed over multiple colors (such as those in a raster image) use the combination with the least contrast. Some [tools](https://www.brandwood.com/a11y/) may help with this.

        ^ Aim for 4.5:1 for all text, not just smaller/body text. This mitigates issues with thinner and less legible fonts.
  - type: dropdown
    id: text-contrast
    attributes: 
      label: All text in the component has at least a 4.5:1 contrast ratio against the colors or imagery behind it.
      options:
        - Passed
        - Failed 1.4.3 (AA)
    validations:
      required: true
  - type: dropdown
    id: non-text-contrast
    attributes: 
      label: All non-textual interface components that are interactive or otherwise convey meaning (icons, form controls, state indicators, etc) have at least a 3:1 contrast ratio with the colors or imagery behind them.
      options:
        - Passed
        - Failed 1.4.11 (AA)
    validations:
      required: true
  - type: dropdown
    id: use-of-color
    attributes: 
      label: Color is not the only way of distinguishing meaningful parts of the interface. For example, red to distinguish an error state, but only as an input border—not as the color of a warning icon.
      options:
        - Passed
        - Failed 1.4.1 (A)
    validations:
      required: true
  - type: textarea
    id: Notes
    attributes:
      label: How to fix
      description: Plans for fixing failed criteria from this test...
    validations:
      required: true