name: Manual Component Test (Keyboard)
description: Script for testing the keyboard accessibility of an individual component.
title: "[Component Name] Keyboard Test"
labels: ["accessibility", "test", "keyboard"]
body: 
  - type: input
    id: url
    attributes:
      label: Component location
      description: A URL to the canonical version of the component in the design system.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        **Instructions:** Navigate the component using the keyboard (Tab to move to the next focusable element; `Shift` + `Tab` to move to the previous one). For each press of the Tab key, ensure the following criteria are true.
  - type: dropdown
    id: no-missed-focus
    attributes:
      label: No elements interactive by other means (like a mouse/pointer) are stepped over.
      options:
        - Passed
        - Failed 2.1.1 (A)
    validations:
      required: true
  - type: dropdown
    id: no-unneeded-focus
    attributes:
      label: No elements that are not intended to be interactive can be focused. 
      options:
        - Passed
        - Failed 2.4.3 (A)
    validations:
      required: true
  - type: dropdown
    id: no-dead-focus
    attributes:
      label: No elements that should be interactive do nothing when activated (Enter and/or Space activation as appropriate).
      options:
        - Passed
        - Failed 2.1.1 (A)
    validations:
      required: true
  - type: dropdown
    id: no-invisible-focus
    attributes:
      label: All visible and focusable controls indicate when they are focused (have a focus CSS style).
      options:
        - Passed
        - Failed 2.4.7 (AA)
    validations:
      required: true
  - type: dropdown
    id: no-invisible-controls
    attributes:
      label: No controls that receive focus are hidden from view. This includes elements for which the focus style is visible but nothing else.
      options:
        - Passed
        - Failed 2.4.11 (AA)
    validations:
      required: true
  - type: dropdown
    id: no-trapped-focus
    attributes:
      label:  It is possible to move focus outside the component, in both directions, and at all times.
      options:
        - Passed
        - Failed 2.1.2 (A)
    validations:
      required: true
  - type: dropdown
    id: no-illogical-order
    attributes:
      label: Elements receive focus in an order that corresponds logically to their visual position within the component. A closed dialog moves focus back to the element the user was on before the dialog was opened.
      options:
        - Passed
        - Failed 2.4.3 (A)
    validations:
      required: true
  - type: dropdown
    id: no-unmanaged-focus
    attributes:
      label: When focus is moved programmatically (by a script) it is to an element with a role and label, such as a button or labeled landmark region. 
      options:
        - Passed
        - Failed 4.1.2 (A)
    validations:
      required: true
  - type: textarea
    id: Notes
    attributes:
      label: How to fix
      description: Plans for fixing failed criteria from this test...
    validations:
      required: true  